# numpy
- 데이터는 행렬로 표현
- 행렬 데이터 빠르게 계산을 해야 합니다
- 행렬 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란 으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

## 행렬 데이터 생성
ndarray : 한가지 데이터 타입만 값으로 사용 가능

In [2]:
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [4]:
array2 = np.array(
    [[1,2,3],
    [4,5,6]]
)
type(array2), array2, array2.ndim, array2.shape

(numpy.ndarray,
 array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

### 행렬의 모양 변경하기

In [11]:
array2.reshape(3,2), array2

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [7]:
## 3차원
array2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

### 행렬 데이터의 선택
offset index, masking

In [9]:
array2[1][::-1]

array([6, 5, 4])

### 데이터 수정

In [12]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [16]:
array2[1][1] = 10
array2[0] = 0   ## 브로드 캐스팅
array2

array([[ 0,  0,  0],
       [ 4, 10, 10]])

In [17]:
array2[0] = [8,7,6]
array2

array([[ 8,  7,  6],
       [ 4, 10, 10]])

#### 한 행렬엔 하나의 타입만 가능

In [18]:
array2[1] = ["hi","im","dokyum"]

ValueError: invalid literal for int() with base 10: 'hi'

### 조건으로 선택

In [19]:
array2

array([[ 8,  7,  6],
       [ 4, 10, 10]])

In [20]:
array2 > 7

array([[ True, False, False],
       [False,  True,  True]])

### 마스킹

In [21]:
idx = array2 > 7
array2[idx]

array([ 8, 10, 10])

In [22]:
array2[idx] = 100
array2

array([[100,   7,   6],
       [  4, 100, 100]])

### 행렬데이터 생성 2

In [24]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

##### .dtype : ndarray data type checker

In [27]:
data.dtype

dtype('float64')

#### .astype : 타입 변경

In [26]:
## astype : 
data2 = data.astype("int")
data2.dtype, data2

(dtype('int64'),
 array([[0, 0, 0],
        [0, 0, 0]]))

In [29]:
data3 = np.ones((2,3,2))
data3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### arrange

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(5,10)

array([5, 6, 7, 8, 9])