# numpy
- 파이썬에서 사용하는 과학계산용 패키지

In [1]:
# 연산
data1 = np.array([1, 2, 3])
data2 = np.array([4, 5, 6])

In [2]:
data1 * 10  # 브로드 캐스팅 : 벡터 * 스칼라

array([10, 20, 30])

In [3]:
data1 * data2  # 같은 형태의 데이터 연산은 같은 위치에 있는 데이터 끼리 연산

array([ 4, 10, 18])

In [5]:
# 객체가 list 
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [6]:
# 객체가 ndarray
data1 + data2

array([5, 7, 9])

In [7]:
# 학생 성적표 만들기

In [8]:
# 1. 60 ~ 100 점까지 10점 단위로 10 * 5 행렬을 만드세요

In [10]:
datas = np.random.randint(6, 11, size=(10,5)) * 10
datas

array([[100,  80,  80,  90,  70],
       [ 60, 100,  70,  60,  80],
       [ 60,  80, 100,  60, 100],
       [ 90,  60, 100,  70,  80],
       [100,  70,  80,  70, 100],
       [100,  90,  60, 100,  70],
       [ 60,  70,  70, 100,  90],
       [100,  60,  80,  80,  60],
       [ 90,  80,  80,  60,  70],
       [ 70,  80,  70,  60, 100]])

In [11]:
# 2. 학생 별 총점 및 평균 데이터 출력

In [18]:
total_point = np.sum(datas, axis=1)
total_point

array([420, 370, 400, 400, 420, 420, 390, 380, 380, 380])

In [21]:
avg_point = np.sum(datas, axis=1) / datas.shape[1]
avg_point

array([84., 74., 80., 80., 84., 84., 78., 76., 76., 76.])

In [22]:
# 3. 평균이 80점 이상인 학생

In [26]:
point_80 = datas[avg_point >= 80]
point_80

array([[100,  80,  80,  90,  70],
       [ 60,  80, 100,  60, 100],
       [ 90,  60, 100,  70,  80],
       [100,  70,  80,  70, 100],
       [100,  90,  60, 100,  70]])

In [27]:
# 4. 

In [32]:
datas,total_point,avg_point

(array([[100,  80,  80,  90,  70],
        [ 60, 100,  70,  60,  80],
        [ 60,  80, 100,  60, 100],
        [ 90,  60, 100,  70,  80],
        [100,  70,  80,  70, 100],
        [100,  90,  60, 100,  70],
        [ 60,  70,  70, 100,  90],
        [100,  60,  80,  80,  60],
        [ 90,  80,  80,  60,  70],
        [ 70,  80,  70,  60, 100]]),
 array([420, 370, 400, 400, 420, 420, 390, 380, 380, 380]),
 array([84., 74., 80., 80., 84., 84., 78., 76., 76., 76.]))

In [33]:
total_point.reshape(10,1)

array([[420],
       [370],
       [400],
       [400],
       [420],
       [420],
       [390],
       [380],
       [380],
       [380]])

In [34]:
# '-1' 은 모르는 쪽 자동 계속
total_point.reshape(-1,1)

array([[420],
       [370],
       [400],
       [400],
       [420],
       [420],
       [390],
       [380],
       [380],
       [380]])

In [35]:
# np.c_ , np.r_

In [36]:
result = np.c_[datas, total_point, avg_point]
result

array([[100.,  80.,  80.,  90.,  70., 420.,  84.],
       [ 60., 100.,  70.,  60.,  80., 370.,  74.],
       [ 60.,  80., 100.,  60., 100., 400.,  80.],
       [ 90.,  60., 100.,  70.,  80., 400.,  80.],
       [100.,  70.,  80.,  70., 100., 420.,  84.],
       [100.,  90.,  60., 100.,  70., 420.,  84.],
       [ 60.,  70.,  70., 100.,  90., 390.,  78.],
       [100.,  60.,  80.,  80.,  60., 380.,  76.],
       [ 90.,  80.,  80.,  60.,  70., 380.,  76.],
       [ 70.,  80.,  70.,  60., 100., 380.,  76.]])

In [38]:
### 5. 데이터 프레임으로 만들기

In [39]:
columns = ["kor","eng","math","sci","cod","tot","avg"]

In [41]:
df = pd.DataFrame(result,columns=columns)
df

kor    eng   math    sci    cod    tot   avg
0  100.0   80.0   80.0   90.0   70.0  420.0  84.0
1   60.0  100.0   70.0   60.0   80.0  370.0  74.0
2   60.0   80.0  100.0   60.0  100.0  400.0  80.0
3   90.0   60.0  100.0   70.0   80.0  400.0  80.0
4  100.0   70.0   80.0   70.0  100.0  420.0  84.0
5  100.0   90.0   60.0  100.0   70.0  420.0  84.0
6   60.0   70.0   70.0  100.0   90.0  390.0  78.0
7  100.0   60.0   80.0   80.0   60.0  380.0  76.0
8   90.0   80.0   80.0   60.0   70.0  380.0  76.0
9   70.0   80.0   70.0   60.0  100.0  380.0  76.0

In [44]:
## 6. 과목별 평균을 구해서 마지막 row에 추가
df.loc[10] = df.mean()
df

kor    eng   math    sci    cod    tot   avg
0   100.0   80.0   80.0   90.0   70.0  420.0  84.0
1    60.0  100.0   70.0   60.0   80.0  370.0  74.0
2    60.0   80.0  100.0   60.0  100.0  400.0  80.0
3    90.0   60.0  100.0   70.0   80.0  400.0  80.0
4   100.0   70.0   80.0   70.0  100.0  420.0  84.0
5   100.0   90.0   60.0  100.0   70.0  420.0  84.0
6    60.0   70.0   70.0  100.0   90.0  390.0  78.0
7   100.0   60.0   80.0   80.0   60.0  380.0  76.0
8    90.0   80.0   80.0   60.0   70.0  380.0  76.0
9    70.0   80.0   70.0   60.0  100.0  380.0  76.0
10   83.0   77.0   79.0   75.0   82.0  396.0  79.2

In [45]:
# 7. 학생별로 평균이 80점이 넘으면 pass 아니면 fail

In [47]:
df["P/F"] = df['avg'].apply(lambda x : 'pass' if x >= 80 else 'fail')
df

kor    eng   math    sci    cod    tot   avg   P/F
0   100.0   80.0   80.0   90.0   70.0  420.0  84.0  pass
1    60.0  100.0   70.0   60.0   80.0  370.0  74.0  fail
2    60.0   80.0  100.0   60.0  100.0  400.0  80.0  pass
3    90.0   60.0  100.0   70.0   80.0  400.0  80.0  pass
4   100.0   70.0   80.0   70.0  100.0  420.0  84.0  pass
5   100.0   90.0   60.0  100.0   70.0  420.0  84.0  pass
6    60.0   70.0   70.0  100.0   90.0  390.0  78.0  fail
7   100.0   60.0   80.0   80.0   60.0  380.0  76.0  fail
8    90.0   80.0   80.0   60.0   70.0  380.0  76.0  fail
9    70.0   80.0   70.0   60.0  100.0  380.0  76.0  fail
10   83.0   77.0   79.0   75.0   82.0  396.0  79.2  fail